### ISSUE TITLE
Exclude directory

### ISSUE THREAD

**Issue by ateuber** [chrieke/mkdocs-exclude-search#1]
We collect meeting notes in a directory and want to exclude all of them. It is a long list of files and every week a new exclude line would need to be added. Therefore it would be nice to be able to just exclude the whole directory.

**Comment by chrieke** [comment]
@ateuber Hi Andreas, thanks for the suggestion. I added a way to exclude all markdown files within a chapter to the plugin, just add `- some_directory/*.md` to the exclude section, also see the updated readme. It works for me, but probably isn't super robust and I didn't yet have time to write proper tests. Please let me know if you encounter any issues!
