### ISSUE TITLE
Exclude unreferenced files from search

### ISSUE THREAD

**Issue by SuibianP** [chrieke/mkdocs-exclude-search#17]
Would it be possible/feasible to implement an option to exclude all unreferenced files (i.e. those that can only be accessed by directly go to its URL)?

**Comment by chrieke** [comment]
Hi @SuibianP, thanks for the suggestion.

Would this mean files that are added to the docs, but are not listed in the mkdocs.yml page tree? Sounds like a good option! I'm not completely sure how you can add those in mkdocs, could you elaborate a bit please? Are unreferenced files still automatically added to the seach index?

**Comment by SuibianP** [comment]
Thanks for the reply @chrieke 😺 

MkDocs by default renders all markdown files, referenced or not. https://github.com/mkdocs/mkdocs/issues/1665

**Comment by chrieke** [comment]
Adressed in https://github.com/chrieke/mkdocs-exclude-search/pull/23 and published with new version 0.6.0, adds a `exclude_unreferenced: true` option.

Description added to readme, please give it a try and report back if there are any issues or it is unclear how to use.

Thanks for the suggestion @SuibianP !

**Comment by chrieke** [comment]
There was an issue with multiple subdirectories, fixed in version 0.6.1.
