### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by Stanzilla** [chrieke/mkdocs-exclude-search#2]
Hey there, just tried this for the first time and got the following error:

```
INFO    -  exclude-search: generated/tags/ 
INFO    -  exclude-search: generated/tags/#contents-grouped-by-tag 
INFO    -  exclude-search: generated/tags/#api 
INFO    -  exclude-search: generated/tags/#misc 
INFO    -  exclude-search: generated/tags/#perks 
INFO    -  exclude-search: generated/tags/#reference 
INFO    -  exclude-search: generated/tags/#tutorial 
Traceback (most recent call last):
  File "/home/stan/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/stan/.local/lib/python3.8/site-packages/mkdocs/__main__.py", line 133, in serve_command
    serve.serve(
  File "/home/stan/.local/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/home/stan/.local/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/stan/.local/lib/python3.8/site-packages/mkdocs/commands/build.py", line 295, in build
    config['plugins'].run_event('post_build', config=config)
  File "/home/stan/.local/lib/python3.8/site-packages/mkdocs/plugins.py", line 96, in run_event
    result = method(**kwargs)
  File "/home/stan/.local/lib/python3.8/site-packages/mkdocs_exclude_search/plugin.py", line 79, in on_post_build
    rec_main_name, rec_subchapter = rec["location"].split("/")[-2:]
ValueError: not enough values to unpack (expected 2, got 1)
```

my config:

```yaml
  - exclude-search:
      exclude:
        - generated/tags.md
        - tags.md
```

**Comment by chrieke** [comment]
Thank you for reporting, will try to look into this in the next couple of weeks and fix/report back.

**Comment by Stanzilla** [comment]
@chrieke Awesome, thank you! Please let me know if you need more info etc, I'm also on the mkdocs-material Gitter if you want to chat.

**Comment by chrieke** [comment]
@Stanzilla Unfortunately could not replicate this case. (It's a bit messy code but currently not able to write proper tests). I edited the readme instructions to be a bit clearer, to exclude a single file, you don't have to provide the directory structure. Could you point me to the repository (if public) where you want to apply this?

**Comment by chrieke** [comment]
One other question, tags.md and generated/tags.md in your case are 2 separate files correct?

**Comment by Stanzilla** [comment]
Yes, they are generated by https://github.com/jldiaz/mkdocs-plugin-tags

The repository is https://github.com/ManticoreGamesInc/platform-documentation

I did not push the changes there put you can add the config example from above to repro. I also tested with just:

```yaml
  - exclude-search:
      exclude:
        - tags.md
``` 

and it still errored.

**Comment by chrieke** [comment]
Created a new version `0.2.1` which fixes a bug where non md files in the search-index broke the mechanism. 

The mkdocs-plugin-tags plugin first creates an aux/tags.md file (outside of the docs folder), but creates two entries in the search index which are already html files. So excluding tags.md would not have the desired purpose, at not point there is a tags.md file in the docs folder.

I'm guessing it runs for you now, but might have not the desired effect of excluding anything tags related. Can you maybe give an example what shows up in the mkdocs search that you want to exclude?

Btw. impressive docs customization!

![image](https://user-images.githubusercontent.com/12833517/106982568-a191a780-6764-11eb-8181-2baab235e1b3.png)

**Comment by Stanzilla** [comment]
Hey, thank you! So the goal is to just have a browsable overview/sitemap when you click on one of the "tag" buttons that is on every page. I do not want that page in search because it was polluting the results with entries that are then just links to the actual pages.

Version `0.2.1` does run now but as you said, the results from `tags.html` are still there.

**Comment by chrieke** [comment]
New version `0.3.0`  added an (for now undocumented) option to ignore all entries generated by mkdocs-plugin-tags. Please update via `pip install mkdocs-exclude-search --upgrade` and add `exclude_tags: True` to your mkdocs.yml configuration of the plugin, see [here](https://github.com/chrieke/mkdocs-exclude-search/blob/main/mkdocs.yml).

Works for me, let me know if you encounter any problems!

**Comment by Stanzilla** [comment]
@chrieke very awesome, thank you so much!

**Comment by chrieke** [comment]
Cool, thank you for the detailed info. Closing then, feel free to reopen if something doesn't work.
