### ISSUE TITLE
Building problem: tests directory is still there

### ISSUE THREAD

**Issue by prescod** [chrieke/mkdocs-exclude-search#20]
https://github.com/chrieke/mkdocs-exclude-search/issues/18#issuecomment-982161236

Maybe if you build by hand it would be better to use a github workflow.

Here is one of mine:

https://github.com/SFDO-Tooling/Snowfakery/blob/main/.github/workflows/release.yml

**Comment by chrieke** [comment]
Thank you for reporting back and the detailed descriptions!

I bumped to 0.5.4 and reuploaded to pypi. Following your unzip instructions, it now shows me the same files without the tests included. Could you please check when installing 0.5.4? Thank you!

**Comment by prescod** [comment]
Looks great. Thanks!
