### ISSUE TITLE
Plugin does nothing if exclude_tags is not defined

### ISSUE THREAD

**Issue by seppi91** [chrieke/mkdocs-exclude-search#3]
Hi @chrieke,
In your most recent version 0.3.0 the absence of `exclude_tags` in the configuration file makes the plugin unuseable as it doesn't exclude anything. I think there is a mistake in the boolean expression at https://github.com/chrieke/mkdocs-exclude-search/blob/main/mkdocs_exclude_search/plugin.py#L49 as it should be an "and" expression.

**Comment by kratsg** [comment]
I noticed the latest version of plugin does not work. Will roll back to 0.2.1

**Comment by chrieke** [comment]
@seppi91 @krastg Thanks for reporting! Fixed in v.0.3.1, also see the new [changelog](https://github.com/chrieke/mkdocs-exclude-search/blob/main/CHANGELOG.md). Finally added some first tests and cleaned up the messy code a bit.

Please let me know if you encounter any problems.
