### ISSUE TITLE
Not excluding.

### ISSUE THREAD

**Issue by sirchampsblanc** [chrieke/mkdocs-exclude-search#38]
Hi, we have a pretty minimal _docs/_ directory and most markdowns are "rendered" dinamically on build with some plugins. Can we exclude things that are not on _docs/_ directory but on _site/_? We're trying to exclude some directories from site/ but we still see them on _searchindex.json_

We have a size problem with our index and we need to reduce it so excluding some directories seems like our best option.

Thanks!

**Comment by chrieke** [comment]
Hi @sirchampsblanc thanks for the feedback! Trying to understand the issue a little better, is it that you customized the [docs_dir](https://www.mkdocs.org/user-guide/configuration/#docs_dir) in the mkdocs.yml configuration, but mkdocs-exclude-search does not pick up on this? Or is there some special configuration that allows you to have mkdocs pull markdown files from two folders `docs` and `site` etc.?

**Comment by sirchampsblanc** [comment]
We have our usual .md on docs/ but we use monorepo to build multiple docs into one so all those documents are pulled while building but not present on our docs/ directory to exclude them.

So our nav would be something like:

`nav:
  - Home: index.md
  - Tutorials: reference/SHOWCASE.md
  - Use case examples:
      - Marketing campaign outcome prediction: notebooks/gettingsta6e9be46c22/getting_started_classification.md
      - House prices prediction model: notebooks/gettingsta663b1badce/getting_started_regression.md
  - Modules Reference:
    - microrrepo1: '!include ./microrepos/2/mkdocs_mercury.yml'
    - microrrepo2: '!include ./microrepos/1/mkdocs_mercury.yml'
  - Contributing: reference/CONTRIBUTING.md
  - Release notes: reference/CHANGELOG.md`
  
  It's a very specific use case so don't worry too much if things can't be done. For now i just filtered the index manually.

**Comment by chrieke** [comment]
Thanks for the detailed info! Finally looked a bit into this, but think I won't be able to implement this in a simple way. Guess have to disappoint you here, I really appreciate the feedback though. Will close for now, if more people face the same challenge, or someone wants to take a stab at a PR for this feature please feel free to reopen this issue.
