### ISSUE TITLE
Mention that Material for MkDocs 9 has search exclusion built in

### ISSUE THREAD

**Issue by johnthagen** [chrieke/mkdocs-exclude-search#40]
It may be worth mentioning in the README that Material for Mkdocs (free tier) now supports search exclusion out of the box

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-exclusion
- https://github.com/squidfunk/mkdocs-material/issues/4714

Thanks so much for creating this plugin while we waited the past couple of years for the upstream library to publish support.

**Comment by chrieke** [comment]
Hey, thanks! Will add a note to the Readme soon. 

Plugin will stay on pypi as it [complements the buildin solution](https://squidfunk.github.io/mkdocs-material/blog/2021/09/26/excluding-content-from-search/#whats-new) e.g. for wildcard exclusions and gives standard mkdocs users an option.
