### ISSUE TITLE
search plugin not being detected

### ISSUE THREAD

**Issue by Paddy-Farmeye** [chrieke/mkdocs-exclude-search#41]
I implemented mkdocs-exclude-search locally and all seemed to work well. Unfortunately, upon deploying to our server I noticed the plugin wasn't taking effect. When looking at the build logs I see the following:
```
DEBUG    -  mkdocs-exclude-search plugin is activated but has no effect as search plugin is deactivated!
``` 
However, I can confirm the `- search` plugin _is_ included directly above `- exclude-search` in our `mkdocs.yml` config.

**Comment by chrieke** [comment]
Hi @Paddy-Farmeye, strange. And locally it works correctly? Is there any other message regarding `search` in the logs on for the server installation?

**Comment by Paddy-Farmeye** [comment]
Ah okay, so I've been comparing the logs and it seems the issue lies here.
locally on mac:
```
DEBUG    -  Config value 'plugins' = {'search': <material.plugins.search.plugin.SearchPlugin object at 0x104687340>, 'exclude-search':
            <mkdocs_exclude_search.plugin.ExcludeSearch object at 0x1047e8c40>, 'print-site': <mkdocs_print_site_plugin.plugin.PrintSitePlugin object at 0x1047e9960>}
```
on ec2 amazon linux:
```
DEBUG    -  Config value 'plugins' = {'material/search': <material.plugins.search.plugin.SearchPlugin object at 0x7f91b1802890>, 'exclude-search':
            <mkdocs_exclude_search.plugin.ExcludeSearch object at 0x7f91af4ba7d0>, 'print-site': <mkdocs_print_site_plugin.plugin.PrintSitePlugin object at
            0x7f91af32f5d0>}
```
Notice how the key has changed form `'search'` to `'material/search'`. I'm not sure why this is, but perhaps this plugin should support both.

**Comment by Paddy-Farmeye** [comment]
@chrieke along with the above detail, here is the corresponding MkDocs update which causes the subsequent bug for this plugin. ref: https://github.com/squidfunk/mkdocs-material/commit/fee799a759a947a68714a59d0279cf8c77eb134a#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L50. As suggested previously, updating the code to compare against 'search' _and_ 'material/search' allow mkdocs-exclude-search to continue to work going forward while maintaining backward compatibility.

**Comment by chrieke** [comment]
Awesome, thank you for debugging this! Fixing now.

**Comment by chrieke** [comment]
New version [0.6.5](https://pypi.org/project/mkdocs-exclude-search/0.6.5/) release. Please let me know if there are any issues left! Thanks again!
