### ISSUE TITLE
Exclusion of a single file does not work anymore

### ISSUE THREAD

**Issue by seppi91** [chrieke/mkdocs-exclude-search#8]
Hi Christoph,
I've just tried your official 0.4.0 release and used it within our documentation repository. It looks like something got changed during refactoring/merge to master. I've tried to exclude a changelog.md which exists in various subfolders

```
/changelog.md
 - subdir/
   - changelog.md
 - another_dir/
   - changelog.md
```

I tried several exclusion rules like `*/changelog.md` or `changelog.md` but none of them worked. When I looked at the code I found this 

https://github.com/chrieke/mkdocs-exclude-search/blob/9df45cf7394c55a1a95428d92b1c12079f4ce603/mkdocs_exclude_search/plugin.py#L129

To my understanding we are cutting the file extension and try to match afterwards the filenames. e.g.
`fnmatch('subdir/changelog.html', *'changelog'?)`

this will be evaluated to `False` as the question mark at the end only matches a single character but not `.html`
So either we are replacing the question mark with a `.html` so it will always use this extension when matching or we ignore the file extension and use `.*`

like to hear your thoughts on it :)

---

edit: also the asterisk at the beginning will unintentionally match some other files like `do-not-match-changelog.html`. Right now this is no issue for me but I don't know if you intended this behavior.

**Comment by chrieke** [comment]
@seppi91 Thanks for the detailed infos, will take a look and hopefully finally resolve this the next couple of days.

**Comment by chrieke** [comment]
Made some updates, see https://github.com/chrieke/mkdocs-exclude-search/pull/11.

If you find the time would be fantastic if you could check again @seppi91 before I put out 0.5.0. You can install from master via `pip install pip+git@github.com:chrieke/mkdocs-exclude-search.git`.

> I've tried to exclude a changelog.md which exists in various subfolders
This should now be possible using the syntax `/*/changelog.md` (or more limited `subdir/*/changelog.md`). Also see the new examples in the documentation.

Replaced the `?` at the end of the `file_name` with rec_file_name[:-1]. This was just to ignore the slash `/` at the end of `rec_file_name`.

What I don't understand why in your example the `rec_file_name` has a `html` ending. At that point in the search index records it should still be `.md`, this is the reason for `.replace('.md', '')` to make the matching more simple. Are you sure this has a `html` ending at that stage?

> also the asterisk at the beginning will unintentionally match some other files like do-not-match-changelog.html
Removed the asterik and added tests for unintenional matching of partial filenames.

**Comment by chrieke** [comment]
Will release this as 0.5.0 but keep the issue open and also do a few more tests.
